services:
  kafka:
    image: apache/kafka:latest
    ports:
      - "9002:9002"
    environment:
      KAFKA_NODE_ID: 1
      KAFKA_PROCESS_ROLES: broker,controller
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_LISTENERS: PLAINTEXT://:9092,CONTROLLER://:9003
      KAFKA_CONTROLLER_QUORUM_VOTERS: "1@kafka:9003"
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9002

  kafka-data-bridge-a:
    build:
      context: .
      dockerfile: dockerfile
    environment:
      SPRING_PROFILES_ACTIVE: dev
      ENABLE_CONSUMER: false
    depends_on:
      - kafka
  kafka-data-bridge-b:
    build:
      context: .
      dockerfile: dockerfile
    environment:
      SPRING_PROFILES_ACTIVE: dev
      READ_KAFKA_TOPIC: insert
    depends_on:
      - kafka
      - kafka-data-bridge-a
