services:
  kafka:
    image: apache/kafka:latest
    ports:
      - "9002:9002"
    environment:
      KAFKA_NODE_ID: 1
      KAFKA_PROCESS_ROLES: broker,controller
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_LISTENERS: PLAINTEXT://:9002,CONTROLLER://:9003
      KAFKA_CONTROLLER_QUORUM_VOTERS: "1@kafka:9003"
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9002

  kafka-data-bridge-producer:
    ports:
      - "9004:9004"
    build:
      context: .
      dockerfile: dockerfile
    environment:
      SPRING_PROFILES_ACTIVE: dev
      ENABLE_CONSUMER: false
      SERVER_PORT: 9004
      SPRING_H2_CONSOLE_SETTINGS_WEB_ALLOW_OTHERS: true
    depends_on:
      - kafka
  kafka-data-bridge-consumer:
    ports:
      - "9005:9005"
    build:
      context: .
      dockerfile: dockerfile
    environment:
      SPRING_PROFILES_ACTIVE: dev
      READ_KAFKA_TOPIC: MOCK_DATABASE_INSERT
      INSERT_KAFKA_TOPIC: MOCK_DATABASE_READ2
      SERVER_PORT: 9005
      SPRING_H2_CONSOLE_SETTINGS_WEB_ALLOW_OTHERS: true
    depends_on:
      - kafka
      - kafka-data-bridge-producer
#stawianie Å›rodowiska
#docker compose up --build
